config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      get "filter"
      get "clear_filters"
    end
  end
  get "up" => "rails/health#show", as: :rails_health_check
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  has_rich_text :content
  validates :date, :topic, :subtopic, :content, presence: true
  scope :order_by_date_desc, -> { order(date: :desc, created_at: :desc) }
  scope :any_topic_of, ->(topic_filter) { where(topic: topic_filter) }
  # scope :keyword, ->(word) { where('content ILIKE ?', "#{word}%") }
  scope :keyword, ->(word) { joins(:rich_text_content).where("action_text_rich_texts.body ILIKE ?", "%#{word}%") }
  scope :order_by_date_desc, -> { order(date: :desc) }
  scope :order_by_topic, -> { order(:topic, :subtopic, date: :desc) }
  scope :order_by_subtopic, -> { order(:subtopic, :topic, date: :desc) }

  def self.topics
    order(topic: :asc).distinct(:topic).pluck(:topic)
  end

  def deletable?
    true
  end

  def editable?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  include SessionsHelper
  include DecoratorHelper
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :initialize_sort, only: :index

  def index
    @items = Item.all
    handle_search
    handle_filter
    handle_sort
    prepare_filter_content
    handle_index_response
  end

  def show
  end

  def new
    @item = Item.new
    @form_cancel_link = items_path
  end

  def edit
    @form_cancel_link = items_path
  end

  def create
    @item = Item.new(item_params)

    # respond_to do |format|
    #   if @item.save
    #     format.html { redirect_to items_path, notice: "Item was successfully created." }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #   end
    # end
    if @item.save
      redirect_to items_path
      flash[:success] = "Item was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @item.update(item_params)
      redirect_to items_path
      flash[:success] = "Item was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
    flash[:success] = "Item was successfully binned"
  end

  def clear_filters
    clear_session(:filter_any_topic_of, :keyword)
    redirect_to items_path
  end

  def filter
    clear_session(:filter_any_topic_of, :keyword)
    session[:keyword] = params[:keyword] || session[:keyword]
    set_session(:any_topic_of)
    redirect_to items_path
  end

  private

  def handle_filter
    @items = ItemQuery.new(session).call
    # %w[any_topic_of].each do |key|
    #   @items = @items.send(key, session["filter_#{key}"]) if session["filter_#{key}"].present?
    # end
  end

  def prepare_filter_content
    @topics = Item.topics
  end

  def initialize_sort
    session[:item_sort_option] = params[:item_sort_option] || session[:item_sort_option] || "date_desc"
  end

  def handle_search
    return if session[:keyword].blank?

    @items = @items.keyword(session[:keyword])
  end

  def handle_sort
    @items = @items.send("order_by_#{session[:item_sort_option]}")
  end

  def handle_index_response
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

    def set_item
      @item = Item.find(params.expect(:id))
    end

    def item_params
      params.expect(item: [ :date, :topic, :subtopic, :content ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decorator_helper.rb
module DecoratorHelper
  def decorate(model_name, view_context = nil, decorator_class = nil)
    (decorator_class || "#{model_name.class}Decorator".constantize).new(model_name, view_context)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def clear_session(*args)
    args.each do |session_key|
      session[session_key] = nil
    end
  end

  def set_session(*args)
    args.each do |session_key|
      session["filter_#{session_key}"] = params[session_key] || session["filter_#{session_key}"]
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/items/_filter_form.html.erb
<div id="items-filter" class="container mb-3 canvas gray100-canvas embossed">
  <div class="container search">
    <%= render partial: 'sort_selection' %>
    <hr class = "search mb-3"></hr>
    <%= form_with(url: filter_items_path, method: "get", class: "form-class", data: {turbo_frame: "items"}) do %>
      <div class="field">
        <%= text_field_tag :keyword, nil, class: "form-control-sm mb-2 search", placeholder: "keyword…", value: session[:keyword], oninput: "this.form.requestSubmit()" %>
      </div>
      <div class="container mb-1 px-1">
        <div class="row">
          <div class="col-4 px-0">
            <fieldset>
              <legend>TOPIC</legend>
              <% @topics.each do |topic| %>
                <%= label_tag nil, class: "chbox-lbl-filters" do %>
                  <%= check_box_tag 'any_topic_of[]', topic, session[:filter_any_topic_of].present? ? session[:filter_any_topic_of].include?(topic) : false, id: "chbox#{topic}", onchange: "this.form.requestSubmit()" %>
                  <%= topic %>
                <% end %>
              <% end %>
            </fieldset>
          </div>

          <div class="container d-flex">
            <%= link_to image_tag('clear_filter.png', class: "button_icon"), clear_filters_items_path, {class: "search searchdelete icon-container"} %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, class: 'admin_form pt-4 my-2') do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class='field'>
    <%= form.label :topic %>
    <%= form.text_field :topic, class: 'form-control' %>
  </div>

  <div class='field'>
    <%= form.label :subtopic %>
    <%= form.text_field :subtopic, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_textarea :content %>
  </div>  

  <div class='actions'>
    <%= form.submit %>
  </div>

  <div class="cancel">
    <%= link_to image_tag('delete.png', class: "table_icon"), @form_cancel_link %>
  </div>    
<% end %>

app/views/items/_item.html.erb
<%# self is the view, which we pass to the decorator to get 'lazy' access to the i18n yml %>
<% item_decorator = decorate(item, self) %>
<%= turbo_frame_tag item do %>
  <div class="row">
    <div class="column"><%= item_decorator.date %></div>
    <div class="column"><%= item_decorator.topic %></div>
    <div class="column"><%= item_decorator.subtopic %></div>
    <div class="column col-1x"><%= item_decorator.first_sentence %></div>
    <%= item_decorator.edit(true, item) %>
    <%= item_decorator.delete(true, item) %>
  </div>
<% end %>

app/views/items/_items_table.html.erb
<div id="items-table" class="container px-0 mb-5 canvas gray100-canvas embossed">
  <div class="admin-table mt-3">
    <%= render @items %>
  </div>
</div>

app/views/items/_sort_selection.html.erb
<form action="/items" method="GET">
  <div class="mt-0">
    <i class="bi bi-sort-alpha-down"></i>
    <select class="form-control-sm mb-2 sort" name="item_sort_option" onchange="this.form.requestSubmit()">
      <option disabled="disabled" selected="selected" value="">Sort by</option>
      <option value="date_desc" <%="selected" if session[:item_sort_option] == "date_desc"%> >date</option>
      <option value="topic" <%="selected" if session[:item_sort_option] == "topic"%> >topic</option>
      <option value="subtopic" <%="selected" if session[:item_sort_option] == "subtopic"%> >subtopic</option>
    </select>
  </div>
</form>

app/views/items/edit.html.erb
<% content_for :title, "Editing item" %>

<%= turbo_frame_tag @item do %>

<%= render "form", item: @item %>

<% end %>

app/views/items/index.html.erb
<% content_for :title, "Items" %>

<div class="container px-1">
  <h4>Items <%= link_to image_tag('add.png', class: "button_icon", alt: 'New item'),
                          new_item_path,
                          data: { turbo_frame: dom_id(Item.new) } %>
  </h4>
  <%= turbo_frame_tag Item.new %>
  <%= turbo_frame_tag 'items-and-filter' do %>
    <%= render 'filter_form' %>
    <%= turbo_frame_tag 'items' do %>
      <%= render 'items_table' %>
    <% end %>
  <% end %>
</div>

app/views/items/index.turbo_stream.erb
<%= turbo_stream.update "items" do %>
  <%= render partial: "items_table" %>
<% end %>
<%= turbo_stream.update "new_item" do %>
  <%= render inline:'' %>
<% end %>
<%#= turbo_stream.prepend "flash", partial: "partials/flashes" %>
<%= turbo_stream.prepend("flash", partial: "layouts/flash") %>

app/views/items/new.html.erb
<% content_for :title, "New item" %>

<%= turbo_frame_tag @item do %>
  <div class="col-md-12 mb-4">
    <%= render 'form', item: @item %>
  </div>
<% end %>

app/views/items/show.html.erb
<% item_decorator = decorate(@item, self) %>
<%= turbo_frame_tag dom_id(@item) do %>
  <div class="canvas gray100-canvas embossed px-2 my-2">
    <div>
      <h1 class='fs-5 mb-1'><%=@item.topic%> - <span class=''><%=@item.subtopic%></span> <%= link_to image_tag('edit.png', class: 'table_icon'), edit_item_path %></h1>
      <h2 class='fs-6'><%= item_decorator.date %></h2>
    </div>
    <div>
      <p class=""><%= @item.content %></p>
    </div>

    <div class="cancel">
      <%= link_to image_tag('delete.png', class: "table_icon"), items_path %>
    </div>        
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message alert alert-<%= flash_type %>"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Techincal Diary" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id='flash' class="flash">  
      <%= render "layouts/flash" %>
    </div>
    <%= yield %>
  </body>
</html>